### ISSUE TITLE
If personnumber is active in checkout it should be marked as mandatory

### ISSUE THREAD

**Issue by andyjohansson** [Billmate/magento#86]

**Comment by andyjohansson** [comment]
Rewrite getadress function as we talked about instead.

**Comment by andyjohansson** [comment]
If getadress is active the personnumber is not marked as mandatory if it payment method is set to invoice or part payment.

**Comment by Boxedsolutions** [comment]
Should be working now.

**Comment by andyjohansson** [comment]
Is it implemented with all supported checkouts @Boxedsolutions?

**Comment by Boxedsolutions** [comment]
Yes as its only is when getaddress is active in firecheckout the field would appear in billing, and on the standard onepage checkout it would be wrong to require as the payment method is selected in later step

**Comment by andyjohansson** [comment]
Not fixed of Billamte Invoice or Part Payment is standard payment method.
![skarmavbild 2015-04-28 kl 14 21 30](https://cloud.githubusercontent.com/assets/4968755/7369367/e7485b76-edb1-11e4-89ad-e57a60c21487.png)

**Comment by Boxedsolutions** [comment]
Fixed now

**Comment by andyjohansson** [comment]
Are now linked with #96.
